modulo-scheduler:
  uri: http://localhost:8083
  connect-timeout-ms: 3000
  read-timeout-ms: 5000
modulo-usuario:
  uri: http://localhost:8081
  connect-timeout-ms: 3000
  read-timeout-ms: 5000
modulo-ia:
  uri: http://localhost:8082
  connect-timeout-ms: 3000
  read-timeout-ms: 90000

spring:
  application:
    name: modulo-mensageria

server:
  port: 8085

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  whatsapp-number: ${TWILIO_WHATSAPP_NUMBER}
  voice-number: ${TWILIO_VOICE_NUMBER}
  webhook-base-url: ${TWILIO_WEBHOOK_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  structured:
    format:
      console: logstash
