modulo-usuario:
  uri: http://localhost:8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: modulo-usuario
              uri: ${modulo-usuario.uri}
              predicates:
                - Path=/pacientes,/auth/login

server:
  port: 8080

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
