modulo-notificacao:
  uri: http://localhost:8084
  connect-timeout-ms: 3000
  read-timeout-ms: 5000

modulo-relatorio-adesao:
  uri: http://localhost:8086
  connect-timeout-ms: 3000
  read-timeout-ms: 5000

spring:
  application:
    name: modulo-scheduler
  datasource:
    url: jdbc:postgresql://localhost:5433/dose_alerta
    username: dose_alerta
    password: dose_alerta
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8083

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

scheduler:
  escalonamento:
    intervalo-ms: 60000
  outbox:
    intervalo-ms: 15000
