spring:
  application:
    name: modulo-relatorio-adesao
  datasource:
    url: jdbc:postgresql://localhost:5433/dose_alerta
    username: dose_alerta
    password: dose_alerta
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8086

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  structured:
    format:
      console: logstash
