modulo-mensageria:
  uri: http://localhost:8085
  connect-timeout-ms: 3000
  read-timeout-ms: 5000

spring:
  application:
    name: modulo-notificacao
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/dose_alerta}
    username: ${DB_USERNAME:dose_alerta}
    password: ${DB_PASSWORD:dose_alerta}
    hikari:
      schema: notificacao
  jpa:
    properties:
      hibernate:
        default_schema: notificacao
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    schemas: notificacao
    default-schema: notificacao

server:
  port: 8084

security:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

scheduler:
  outbox:
    intervalo-ms: 15000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  structured:
    format:
      console: logstash
