spring:
  application:
    name: modulo-usuario
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/dose_alerta}
    username: ${DB_USERNAME:dose_alerta}
    password: ${DB_PASSWORD:dose_alerta}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8081

security:
  jwt:
    issuer: modulo-usuario
    public-key: ${JWT_PUBLIC_KEY}
    private-key: ${JWT_PRIVATE_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  structured:
    format:
      console: logstash
